import { NextResponse } from 'next/server';
import { Resend } from 'resend';

// Initialize Resend with the API key from environment variables
const resend = new Resend(process.env.RESEND_API_KEY || 're_placeholder_key');

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { name, email, phone, product, message } = body;

    // Validate inputs
    if (!name || !email || !message) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Gorgeous HTML Email Template
    const htmlTemplate = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>New Lead: ${product}</title>
      </head>
      <body style="font-family: 'Inter', Helvetica, Arial, sans-serif; background-color: #f4f4f5; padding: 40px 0; margin: 0;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
          <!-- Header -->
          <div style="background-color: #4F46E5; padding: 30px 40px; text-align: center;">
            <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">PrintStyle</h1>
            <p style="color: #c7d2fe; margin: 8px 0 0 0; font-size: 14px;">New Customer Inquiry</p>
          </div>
          
          <!-- Content -->
          <div style="padding: 40px;">
            <h2 style="color: #0F172A; font-size: 20px; margin-top: 0; margin-bottom: 24px; border-bottom: 2px solid #f1f5f9; padding-bottom: 12px;">Lead Details</h2>
            
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #64748B; width: 140px; font-size: 14px;">Customer Name</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #0F172A; font-weight: 500; font-size: 15px;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #64748B; font-size: 14px;">Email Address</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #4F46E5; font-weight: 500; font-size: 15px;"><a href="mailto:${email}" style="color: #4F46E5; text-decoration: none;">${email}</a></td>
              </tr>
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #64748B; font-size: 14px;">Phone Number</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #0F172A; font-weight: 500; font-size: 15px;">${phone || '<span style="color: #94a3b8; font-style: italic;">Not provided</span>'}</td>
              </tr>
              <tr>
                <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #64748B; font-size: 14px;">Interested In</td>
                <td style="padding: 12px 0; border-bottom: 1px solid #f1f5f9; color: #0F172A; font-weight: 600; font-size: 15px; color: #4F46E5;">${product}</td>
              </tr>
            </table>

            <div style="margin-top: 32px; background-color: #f8fafc; border-radius: 8px; padding: 24px; border: 1px solid #e2e8f0;">
              <h3 style="color: #475569; font-size: 14px; margin-top: 0; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.05em;">Customer Message:</h3>
              <p style="color: #334155; font-size: 15px; line-height: 1.6; margin: 0; white-space: pre-wrap;">${message}</p>
            </div>
            
            <div style="margin-top: 32px; text-align: center;">
              <a href="mailto:${email}" style="display: inline-block; background-color: #4F46E5; color: #ffffff; font-weight: 500; text-decoration: none; padding: 14px 28px; border-radius: 6px; font-size: 15px;">Reply to Customer</a>
            </div>
          </div>
          
          <!-- Footer -->
          <div style="background-color: #f8fafc; padding: 24px; text-align: center; border-top: 1px solid #e2e8f0;">
            <p style="color: #94a3b8; margin: 0; font-size: 13px;">This email was automatically generated by your PrintStyle Website.</p>
          </div>
        </div>
      </body>
      </html>
    `;

    // Send the email using Resend
    const { data, error } = await resend.emails.send({
      from: 'PrintStyle Leads <onboarding@resend.dev>', // Resend's testing domain
      to: ['priyankakashyap75730@gmail.com', 'shubhamrajvanshi2001@gmail.com'],
      replyTo: email,
      subject: `🎉 New Website Lead: ${name} is interested in ${product}`,
      html: htmlTemplate,
    });

    if (error) {
      console.error('Resend API Error:', error);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json(
      { message: 'Email sent successfully', data },
      { status: 200 }
    );
  } catch (error: any) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to send email' },
      { status: 500 }
    );
  }
}
